USE movie_empire;
CREATE TABLE Movie(
MovieId			INTEGER		NOT NULL,
MovieTitle		CHAR(50)	NOT NULL,
MovieYear		integer		NOT NULL,
MovieTime		integer		not null,
MovieLang		CHAR(50)	NOT NULL,
MovieDtRel		DATE		NULL,
MovieRelCountry	CHAR(9)		NOT NULL,
CONSTRAINT		Movie_PK	PRIMARY KEY(MovieId)
);

CREATE TABLE Actor(
ActID		INTEGER		NOT NULL,
ActFname	CHAR(20)	NOT NULL,
ActLname	CHAR(20)	NOT NULL,
ActGender	CHAR(1)		NOT NULL,
CONSTRAINT		Actor_PK	PRIMARY KEY(ActID)
);

CREATE TABLE Director(
DirId		INTEGER		NOT NULL,
DirFname	CHAR(30)	NOT NULL,
DirLname	CHAR(30)	NOT NULL,
CONSTRAINT		Director_PK	PRIMARY KEY(DirId)
);

CREATE TABLE Movie_Direction(
DirId		INTEGER		NOT NULL,
MovieId		INTEGER		NOT NULL,
CONSTRAINT		Director_FK	FOREIGN KEY(DirId) REFERENCES Director(DirId),
CONSTRAINT		Movie_FK	FOREIGN KEY(MovieId) REFERENCES Movie(MovieId)
);

CREATE TABLE Movie_Cast(
ActID		INTEGER		NOT NULL,
MovieId		INTEGER		NOT NULL,
MovieRole	CHAR(30)	NULL,
CONSTRAINT		Movie_Cast_FK	FOREIGN KEY(MovieId) REFERENCES Movie(MovieId),
CONSTRAINT		Actor_FK	FOREIGN KEY(ActID) REFERENCES Actor(ActID)
);

CREATE TABLE Genres(
GenId		INTEGER		NOT NULL,
GenTitle	CHAR(20)	NULL,
CONSTRAINT		Genres_PK	PRIMARY KEY(GenId)
);

CREATE TABLE Movie_Genres(
MovieId		INTEGER		NOT NULL,
GenId		INTEGER		NOT NULL,
CONSTRAINT		Movie_Gen_FK	FOREIGN KEY(MovieId) REFERENCES Movie(MovieId),
CONSTRAINT		Genres_FK	FOREIGN KEY(GenId) REFERENCES Genres(GenId)
);

CREATE TABLE Reviewer(
RevId		INTEGER		NOT NULL,
RevName		CHAR(30)	NULL,
CONSTRAINT		Reviewer_PK	PRIMARY KEY(RevId)
);

CREATE TABLE Rating(
MovieId		INTEGER		NOT NULL,
RevId		INTEGER		NOT NULL,
RevStars	CHAR(30)		NULL,
NumOfRating	CHAR(45)    	NULL,
CONSTRAINT		Movie_Rate_FK	FOREIGN KEY(MovieId) REFERENCES Movie(MovieId),
CONSTRAINT		Reviewer_FK	FOREIGN KEY(RevId) REFERENCES Reviewer(RevId)
);
